import React, {useState, useEffect} from "react";
import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../src/components/header/header'
import Search from '../src/components/search/search'
import MovieList from '../src/components/movielist/MovieList'


export default function Home() {
  const [movies, setMovies] = useState([]);// an empty array, the movies will be displayed in an array
  const [searchValue, setSearchValue] = useState('');//an empty string because here is the space tu put my search

const getMovieRequest = async (searchValue) =>{
  const url =  `http://www.omdbapi.com/?s=${searchValue}&apikey=f2ab93fd`

  //here we put a space in memory the request to the api, first the url to the api
  const response = await fetch(url); //then the fetch (the action to fetch the api with the url described up)
  const responseJson = await response.json(); // idk what are we doing here

  if (responseJson.Search){ // put the state of the movies just if we have a search 
    setMovies(responseJson.Search);
  }
};

useEffect (()=>{
  getMovieRequest(searchValue);
},[searchValue]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Search Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ResponsiveAppBar heading="Movie"/>
      </header>
      <main >
      <div id="searchContainer">
         <Search searchValue={searchValue} setSearchValue={setSearchValue} ></Search>
      </div>
          <div >
            <div id="container">
                <MovieList movies={movies} />
            </div>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
